karma-runner/karma-browserstack-launcher

README.md, index.js
This is required by browserstack to enable usage of ios simulators.
=> Pass through the 'real_mobile' argument

package.json
Includes a bug fix for network errors.
Previously, if a browerstack request errored then it would exit the process and leave the browserstack tunnel wide open.
=> Updated browserstack library

index.js
BrowserStack has recently implemented rate limiting on their API at 120 requests per minute.  Based on the number of browsers you're using, the time each browser takes, and the number of parallel workers your BrowserStack plan supports, this number is now easily reachable.
Exposing the timeout value when polling queued workers allows us to reduce the total number of API calls.  Increasing this value may result in a delay reporting that a test has changed from queued to running, but we would rather lose those few seconds than reach the throttling limit.
=> Exposing the polling timeout setting.

index.js
Since the default changes based on the type of device on browserstack,
we cannot know the correct default. For this reason we will only use the
value when given.
https://github.com/karma-runner/karma-browserstack-launcher/issues/33
=> Do not use a default value for "real_mobile"

index.js, package.json
The browserstacktunnel-wrapper package used by Karma was relying on
outdated interface to the BrowserStackTunnel binary; some options no longer
work, others were not supported.
For back compat fallback to the old tunnelIdentifier option was added.
Maybe the fallback is not needed if the minor is bumped?
The commit that updated the options was https://github.com/pghalliday/node-BrowserStackTunnel/commit/0b44eab9f712998439168b07344cfa062902e79f
=> fix: Update browserstacktunnel-wrapper & others

README.md, index.js
Node-BrowserStackTunnel allows for the specifying of the binary's bin path. The proposed PR allows for an option to be set in the karma config, browserstack object and it will pass through to node-BrowserStackTunnel.
```
browserStack: {
project: 'browserstack-karma',
...
binaryBasePath: '/Applications/'
},
```
Then just as they do in the Node-BrowserStackTunnel, I switch on OS and apply the appropriate  property:
```
osxBin: 'your_bin_dir', // optionally override the default bin directory for the OSX binary
linux32Bin: 'your_bin_dir', // optionally override the default bin directory for the Linux 32 bit binary
linux64Bin: 'your_bin_dir', // optionally override the default bin directory for the Linux 64 bit binary
win32Bin: 'your_bin_dir', // optionally override the default bin directory …
```
=> feat(config):  added ability to specify binary base path

gruntfile.js, index.js, worker-manager.js, worker.js
Uses a shared poller to fetch and update the status of workers; helps reduce the no. of requests made to BrowserStack.
Ref #30
Let me know if there's scope for improvement or if an alternative approach is required.
=> feat: Global poller for updating worker status

index.js
fixes #47
Inherit base launcher for eventing compatibility and override `forceKill`(that's the only one not overridden) based on the one here (https://github.com/karma-runner/karma/blob/master/lib/launcher.js#L74-L80) but using `q` as Promise.
=> inherit base launcher and override forceKill

index.js
A [recent change](https://github.com/karma-runner/karma-browserstack-launcher/commit/2dcb6adde8fc16b1c8b3e8c0a1b9d28b4dae3c09) broke the ability to run tests parallely using multiple `BrowserStackLocal` binary instances.
This fix restores that functionality.
The [browserstacktunnel-wrapper](https://github.com/pghalliday/node-BrowserStackTunnel) module requires the `localIdentifier` option set, whereas the [browserstack](https://github.com/scottgonzalez/node-browserstack/) module requires the `tunnelIdentifier` option when creating a browser-worker.
=> fix: Pass localIdentifier to browserstacktunnel-wrapper

README.md, index.js
Providing `startTunnel` as `false` currently sets the `tunnelIdentifier` for the browser-worker to a random string, causing tests to fail.
If a tunnelIdentifier or localIdentifier is set in config, it is used as the tunnelIdentifier
when creating a new browser-worker. This is useful if the tunnel is created outside of `karma` by running the binary, optionally with a `localIdentifier` parameter.
If not set and startTunnel is true, we generate a random `localIdentifier` and `tunnelIdentifier`.
=> fix: Avoid setting tunnelIdentifier if startTunnel is false

README.md, index.js, package.json
Added the ability to set the proxy-settings on the BrowserstackLocal-tunnel. I needed those to be able to use the plugin from behind a corporate proxy. 
Sorry for the resubmit, I did use the wrong email-address for the commit and ran into issues with the google-licensing bot.
=> Add proxy settings for BrowserstackLocal

index.js
Fixes #17 
One scenario where Karma reports a failed capture even when things are fine is:
1. Creating a worker with captureTimeout starts [the timer](https://github.com/karma-runner/karma-browserstack-launcher/blob/dba17478074bd12e03a1894579b7de93c31c110f/index.js#L194)
2. Webpage in browser connects to Karma before we're able to poll and determine that the work has entered 'running' state (`captured = true`). Particularly happens with Safari on MacOSX
3. Tests complete and worker is killed before capture timeout occurs, setting `captured = false`
4. On timeout, we check the 'captured' state and find it to be false, causing a restart of the worker
Here's [a test run](https://travis-ci.org/shirish87/angular/jobs/101395993#L899) with some extra logging for this scenario.
=> fix: Capture timeout occurs even after tests have run successfully

README.md
Received feedback from a few users who tried using their username/password.
=> Remove hint that email/password can be supplied as credentials

index.js
Now storing the URL and if session is started with an undefined URL, we reuse the previous URL
Fixes #63
=> fix: issue with url being 'undefined' after disconnect

index.js
Fix for proxy credentials containing special characters such as `?`.
=> fix: urlencode proxy username and password

worker-manager.js
Fixes https://github.com/karma-runner/karma-browserstack-launcher/issues/62
I reproduced #62 that happens sometimes. After some live debugging in my stucked process, I discovered the workers were still polling, confirming @willfrew findings
The main reason is because `startPolling` function calls `client.getWorkers` which is a request to browserstack. This call is asynchronous, and therefore, if `stopPolling` is called when `client.getWorkers` happens, polling won't stop.
(See https://github.com/karma-runner/karma-browserstack-launcher/pull/68/files#diff-63071f9e1d26dc7201e29523f37a0873R58)
`stopPolling` was doing 2 things:
* call `clearTimeout` to stop `startPolling` to be called. This has only effect is `startPolling` is not being processed.
* set `isPolling = false`. I don't see any …
=> Use separate property to shutdown workers

README.md, browserstack-reporter.js, index.js
This marks the status of any failed Browserstack Automate session to "error", so that the session appears red in the Browsertack web interface (without this all builds appear green).
solves #72
=> feat: adding BrowserStack reporter

README.md, index.js, package.json
Browserstack uses the `name` property in the browser configuration
to uniquely name sessions within a specific build. If these sessions
do not have a unique name, and are executed sequentially (or with a
concurrency < total # of browsers), browserstack's UI will overwrite
previous results with new ones. In cases where a karma test run is
executed on multiple browsers, this isn't really desirable.
While I was at it, I also incorporated changes from #71, and
updated the README to also include documentation for that change. With
this patch, `name`, `project`, and `build`, may all be overridden on
a per browser basis.
=> Permit overriding `name`, `build`, and `project` on a per-browser basis.

README.md, index.js
I would like to configure the `forcelocal` flag through my `karma.conf` file. It doesn't appear like this gets passed through to the tunnel. This PR passes along the `forcelocal` flag.
=> feat: pass forcelocal to tunnel

package.json
Use browserstacktunnel-wrapper 2.0.1 as it allows users to run tests behind proxy (pghalliday/node-BrowserStackTunnel/pull/28).
=> Upgrade to browserstacktunnel-wrapper 2.0.1

index.js, package.json
Attempting to solve #126.  This PR would depend on https://github.com/pghalliday/node-BrowserStackTunnel/pull/31 passing, merged, and being released first.
=> Added support for the enableLoggingForApi property

package.json
It patches a high risk vulnerability of https-proxy-agent dependency.
https://nodesecurity.io/advisories/593
=> Upgrade browserstack to v1.5.1, which patches a HIGH risk vulnerability of https-proxy-agent dependency

index.js
When using the `.then($1, $2)` function, any errors thrown from `$1` will *not* be delegated to `$2`. Changing to `.then($1).catch($2)` makes sure that even errors from `$1` gets delegated to `$2`.
Found by this proposed standard rule: standard/eslint-config-standard#129
=> Catch errors thrown by client.createWorker

README.md
👋 Hey there! 
I ended up noticing a few discrepancies in the documentation when I was setting this up, so here I am!
- updated environment variables in document from `BROWSER_STACK_...` to `BROWSERSTACK_...`
- removed documentation about `binaryBasePath` which doesn't seem to be available any longer.
- #144
=> docs: updated environment variables to the correct names

README.md
Removed `timezone` cap from README since its not supported.
=> removed incompatible cap from readme

README.md, index.js
This MR will again pass in the config options `tunnelIdentifier`,
`localIdentifier` and `forceLocal` to the npm package that
creates the Browserstack Local tunnel.
Resolves #155 #156
=> fix: make configuration options work again

index.js
When these config values are absent the error from browserstack is in terms 
of 'username' and 'password', but our config values use different property names.
=> feature(config): exit with info if missing username/password
